Open wifi fix & small improvements
husarion/panther_rutx11 pull request #1
Opened 2023-09-19 09:02 UTC by reastdignity

2023-09-19 14:22 UTC, KmakD requested changes

2023-09-19 14:22 UTC, KmakD commented on setup_wifi.py
> +# Requires RUTX11 device with configuration set by first_setup.sh script - by default done by Husarion during production.
```suggestion
# Requires RUTX11 device with configuration set by factory_settings.sh script - by default done by Husarion during production.  
```

2023-09-19 14:22 UTC, KmakD commented on setup_wifi.py
> +import sys
```suggestion
import io
import json
import os
from pssh.clients import SSHClient
import pssh.exceptions 
import subprocess
import sys
import time
```
Lest keep alphabetical order

2023-09-19 14:22 UTC, KmakD commented on setup_wifi.py
> +    for x in data:
```suggestion
    for index, key in enumerate(data, start=1):
```
This can be simplified. This way you don't have to worry about incrementing index later.

2023-09-19 14:22 UTC, KmakD commented on setup_wifi.py
> +        priority += 1
```suggestion
    for priority, x in enumerate(config["wifi_client"], start=1):
        cmd += set_multi_wifi(x["ssid"], x["password"], priority)
```
same as above

2023-09-19 14:22 UTC, KmakD commented on setup_wifi.py
> +        if used_radio != 'radio'+str(wifi_client_radio):
```suggestion
        if used_radio != 'radio' + str(wifi_client_radio):
```

2023-09-19 14:22 UTC, KmakD commented on setup_wifi.py
> +            cmd +="uci set wireless.multi_wifi.device='radio"+str(wifi_client_radio)+"';"
```suggestion
            cmd += "uci set wireless.multi_wifi.device='radio" + str(wifi_client_radio) + "';"
```

2023-09-19 14:22 UTC, KmakD commented on setup_wifi.py
> +import click
```suggestion
from click import secho
```
Lets import only necessary methods

2023-09-20 08:30 UTC, KmakD requested changes

2023-09-20 08:30 UTC, KmakD commented on setup_wifi.py
> +    secho("Waiting for establishing internet connection. Try {}/50".format(try_count))
```suggestion
    secho("Waiting to establish an internet connection. Try {}/50".format(try_count))
```

2023-09-20 08:30 UTC, KmakD commented on setup_wifi.py
There is inconsistency in using quotation marks in the file. Sometimes it's `"` and sometimes `'`.

2023-09-20 09:35 UTC, reastdignity commented on setup_wifi.py
> +    secho("Waiting for establishing internet connection. Try {}/50".format(try_count))
Applied

2023-09-20 09:41 UTC, KmakD approved these changes

2023-09-20 09:45 UTC, merged